### PR TITLE
Feat: A simple and minimalist comment system.

### PR DESCRIPTION
**Pull request by MHuiG**
The addition of this comment system can give users more choices.

Minivaline is an optimized Valine, just like its name.

After all work is completed, your project will be included in AWESOME-MiniValine

That sounds great！

https://github.com/MiniValine/AWESOME-MiniValine

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/MiniValine/AWESOME-MiniValine">MiniValine/AWESOME-MiniValine</a></strong></div><div>:sunglasses: Minimalist MiniValine, AWESOME MiniValine! - MiniValine/AWESOME-MiniValine</div></blockquote>

### CODE REVIEW

**Comment by MHuiG** [comment]
I'm back!

**Comment by YunYouJun** [comment]
Yeah, that's cool. Welcome.

Does it have a function about `visitor`? (I cannot find it.)

If it doesn't exist, can you remove `minivaline-visitor.pug`, and just use `minivaline.pug`?

**Comment by MHuiG** [comment]
OK

**Comment by YunYouJun** [comment]
Merged. Thanks.
Looking forward to the growth of MiniValine.

**Comment by MHuiG** [comment]
MiniValine version 2.x beta :point_right: [内测邀请](https://github.com/MiniValine/MiniValine) :point_left:

**Comment by YunYouJun** [comment]
Yeah, I will update it when I have time.

**Comment by YunYouJun** [comment]
Get it done!

**Pull request merged**
