### PR TITLE
Feat: A simple and minimalist comment system

### PR DESCRIPTION
**Pull request by MHuiG**
The addition of this comment system can give users more choices.

After all work is completed, your project will be included in AWESOME-MiniValine.

That sounds great！

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/MiniValine/AWESOME-MiniValine">MiniValine/AWESOME-MiniValine</a></strong></div><div>:sunglasses: Minimalist MiniValine, AWESOME MiniValine! - MiniValine/AWESOME-MiniValine</div></blockquote>

### CODE REVIEW

**Comment by YunYouJun** [comment]
Yeah, that's cool.
Can you provide more info about MiniValine?
What's the difference between MiniValine and Valine?

image
image

MiniValine is not smaller, but ten times larger than valine. Why?

**Comment by MHuiG** [comment]
More «MiniValine» information [here](https://github.com/MiniValine/MiniValine).
More «Valine» information [here](https://valine.js.org/).

**Comment by YunYouJun** [comment]
@MHuiG Yeah, I know it. But why is it so big? MiniValine is `887.82 KB`, and valine is `73.2 KB`.
It looks more like MaxiValine not MiniValine.
If it's so big, I won't be able to load it on the homepage to count visitors.
Will the development of minivaline shrink its size? Or what is the reason for its size?

**Comment by MHuiG** [comment]
We have found the main cause of the problem.
The current package size of v1.2.17 is 163.34 KB, gzip 53.27 KB,
But don't worry, packaging optimization will continue.

https://app.bundle-analyzer.com/gh/MiniValine/MiniValine

**Comment by YunYouJun** [comment]
@MHuiG This size is acceptable. But still bigger than valine. 
Just my suggestion:
- Can you seperate a core file like `minivaline.pure.min.js` (just include core lib)?
- Few people use latex in comments. Introduced `minivaline.math.min.js` only when the user turns on math. (Of course, highlight.js, markdown css, too)
When your size is smaller than valine, MiniValine deserves it, will also be used by more people because of this feature.

If it has no special features, I won't merge it until it is smaller than valine.
Thank you for understanding.

**Comment by MHuiG** [comment]
Stay tuned ...

**Comment by YunYouJun** [comment]
@MHuiG Yeah, I am looking forward to it becoming a more lightweight comment system. Deserves mini.

**Comment by MHuiG** [comment]
First of all, Happy April Fool's Day.

mini

valine

**Comment by YunYouJun** [comment]
Yeah, that's cool.

But [Minivaline.github.io](https://minivaline.github.io/) seems to be something wrong.

I have cleared the cache.

image

> By the way, if you want to let more people know about it, you can try to create a post on the `分享创造` node of [V2EX](https://www.v2ex.com/).

**Comment by MHuiG** [comment]
Yes, I used the configuration of the development environment in a production environment, but now, it works perfectly.

**Comment by MHuiG** [comment]
git


I learned that you are using github issues as a commenting system, why not try this?

[Gitalk](https://gitalk.github.io/)

image

**Comment by YunYouJun** [comment]
I did use gitalk as a commenting system in the past.
But for some reason I stopped using it.
https://yun.yunyoujun.cn/guide/third-party-support.html#github-issue-%E4%B8%8E-gitalk

**Comment by MHuiG** [comment]
image
valine 1.4.0 version has not been released. 
[This site uses an unreleased version.](https://valine.js.org/)
valine added MathJax in version 1.4.0, so the package becomes larger.
This MathJax code looks familiar to me, it seems to be the version I have used before, it is not compatible with IE.
It seems that the new version of valine is not going to be compatible with IE anymore.

**Comment by MHuiG** [comment]
Yes, since the bug appeared in Gitalk, I have closed the github email reminder and added other comment systems.

**Comment by MHuiG** [comment]
image

New milestone, minivaline is now only 11KB.

**Comment by MHuiG** [comment]
Another interesting thing is that the renovate bot is not added like this, I think the valine author has discovered my project.

image


image

**Pull request closed without merging**
